name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.13"
        cache: true
        cache-dependency-path: |
          ./pdm.lock

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2

    - name: Install dependencies
      run: pdm install --dev

    - name: Run tests
      run: pdm run test

    - name: Run all checks
      run: pdm run all-checks

    - name: Update version in pyproject.toml
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Updating version to ${{ steps.gitversion.outputs.semVer }}"
        sed -i "s/version = \".*\"/version = \"${{ steps.gitversion.outputs.semVer }}\"/" pyproject.toml

    - name: Build package
      if: github.ref == 'refs/heads/main'
      run: pdm build

#    - name: Publish package to PyPI
#      if: github.ref == 'refs/heads/main'
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        password: ${{ secrets.PYPI_API_TOKEN }}
